# Site settings
title: Development as Freedom
email: duongthuvn@protonmail.com
author:             Anh Thu Duong
url:                "https://non-ceterisparibus.github.io"

# Social Profiles
twitter_username: duongthuvn
github_username: non-ceterisparibus
linkedin_username:

# Build settings
markdown: kramdown
gems:
  - octopress-paginate
paginate: 4
paginate_path:      "/:categories/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site